"""
Clean human-authored PRs by removing:
1. Bot accounts registered as User
2. PRs with AI agent-generated attribution in the body

Removed entries are written to a quarantine file for tracking.
Run AFTER combining language splits and BEFORE classification.

Usage:
    python clean_human_prs.py --discover   # Print top authors to find bots
    python clean_human_prs.py --dry-run    # Preview what would be removed
    python clean_human_prs.py              # Clean for real
"""

from __future__ import annotations

import json
import shutil
import sys
from collections import Counter
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[2]))
from scripts.utils.config import HUMAN_PR_DIR, PROCESSED_DIR

# ============================================================================
# Configuration
# ============================================================================

HUMAN_PR_FILE = HUMAN_PR_DIR / "human_authored_prs.jsonl"
QUARANTINE_DIR = PROCESSED_DIR / "excluded_human_prs"
QUARANTINE_FILE = QUARANTINE_DIR / "excluded_human_prs.jsonl"

# Known bot accounts that register as author_type: "User"
BOT_USERNAMES = {
    # Pre-existing blocklist
    "juliaregistrator",
    "dependabot",
    "renovate",
    "greenkeeper",
    "imgbot",
    "allcontributors",
    "codecov",
    "stale",
    "semantic-release-bot",
    "github-actions",
    "pyup-bot",
    "snyk-bot",
    "whitesource-renovate",
    "mend-bolt-for-github",
    "depfu",
    "fossabot",
    "netlify",
    "vercel",
    "railway-app",
    "codeclimate",
    # Discovered via --discover on human PRs
    "brewtestbot",
    "kibanamachine",
    "azure-sdk",
    "github-automation-metabase",
    "backport-action",
    "fw-bot",
    "miss-islington",
    "fleet-release",
    "comfy-pr-bot",
    "ydbot",
    "fern-support",
    "truecharts-admin",
    "weblate",
    "ghost",
}

# Strings in PR body (lowercased) indicating the PR was GENERATED by an agent,
# not merely assisted. These are PRs that should have been collected as AI PRs
# but slipped into the human set due to search query gaps.
AI_GENERATED_MARKERS = [
    # Claude Code - generated PRs use one or both of these
    "generated with [claude code]",
    "generated by [claude code]",
    "co-authored-by: claude <noreply@anthropic.com>",
    # GitHub Copilot coding agent suffix (bot-generated PRs)
    "start copilot coding agent suffix",
    # Devin bot-generated PRs
    "devin-ai-integration[bot]",
    # Codegen bot-generated PRs
    "codegen-sh[bot]",
]


# ============================================================================
# Loading
# ============================================================================


def load_entries(path: Path) -> list[dict]:
    """Load all entries from a JSONL file, skipping malformed lines."""
    if not path.exists():
        raise FileNotFoundError(f"{path} not found")

    entries = []
    skipped = 0
    with open(path, "r", encoding="utf-8") as f:
        for line_num, line in enumerate(f, 1):
            if not line.strip():
                continue
            try:
                entries.append(json.loads(line))
            except json.JSONDecodeError as e:
                skipped += 1
                print(f"  WARNING: Skipped malformed line {line_num}: {e}")
                if skipped <= 3:
                    print(f"    Content preview: {line[:120]}...")

    if skipped:
        print(f"  Skipped {skipped} malformed lines out of {skipped + len(entries)} total")

    return entries


# ============================================================================
# Discovery Mode
# ============================================================================


def discover_suspicious_authors(entries: list[dict], top_n: int = 30) -> None:
    """Print top PR authors to help identify bot accounts."""
    author_counts = Counter(e.get("author", "unknown") for e in entries)

    print(f"Top {top_n} authors by PR count:\n")
    print(f"  {'Author':<35} {'PRs':>6}  {'In blocklist?'}")
    print(f"  {'-'*35} {'-'*6}  {'-'*13}")

    for author, count in author_counts.most_common(top_n):
        blocked = "YES" if author.lower() in BOT_USERNAMES else ""
        print(f"  {author:<35} {count:>6}  {blocked}")

    # Also flag authors that appear in many distinct repos
    author_repos: dict[str, set] = {}
    for e in entries:
        author = e.get("author", "unknown")
        repo = e.get("repo_full_name", "unknown")
        author_repos.setdefault(author, set()).add(repo)

    print(f"\n\nAuthors active in 20+ repos (likely bots):\n")
    print(f"  {'Author':<35} {'PRs':>6}  {'Repos':>6}  {'In blocklist?'}")
    print(f"  {'-'*35} {'-'*6}  {'-'*6}  {'-'*13}")

    suspicious = [
        (author, author_counts[author], len(repos))
        for author, repos in author_repos.items()
        if len(repos) >= 20
    ]
    suspicious.sort(key=lambda x: x[2], reverse=True)

    for author, pr_count, repo_count in suspicious:
        blocked = "YES" if author.lower() in BOT_USERNAMES else ""
        print(f"  {author:<35} {pr_count:>6}  {repo_count:>6}  {blocked}")

    not_blocked = [a for a, _, _ in suspicious if a.lower() not in BOT_USERNAMES]
    if not_blocked:
        print(f"\n  Review these {len(not_blocked)} unblocked multi-repo authors.")
        print(f"  Add confirmed bots to BOT_USERNAMES and re-run.")


# ============================================================================
# Cleaning Logic
# ============================================================================


def check_bot_username(pr: dict) -> str | None:
    """Return reason string if author is a known bot, else None."""
    author = pr.get("author", "")
    if author.lower() in BOT_USERNAMES:
        return f"bot_username:{author}"
    return None


def check_ai_generated(pr: dict) -> str | None:
    """Return reason string if PR body indicates agent-generated PR, else None."""
    body = pr.get("body") or ""
    body_lower = body.lower()
    for marker in AI_GENERATED_MARKERS:
        if marker in body_lower:
            return f"ai_generated:{marker}"
    return None


def clean_human_prs(dry_run: bool = False) -> dict:
    """
    Clean human PR file in-place, quarantining removed entries.

    Returns summary statistics.
    """
    entries = load_entries(HUMAN_PR_FILE)
    print(f"Loaded {len(entries):,} human PRs from {HUMAN_PR_FILE.name}")

    # Classify each entry
    clean = []
    excluded = []

    for pr in entries:
        reason = check_bot_username(pr) or check_ai_generated(pr)
        if reason:
            pr["_exclusion_reason"] = reason
            excluded.append(pr)
        else:
            clean.append(pr)

    # Summary
    bot_count = sum(
        1 for e in excluded if e["_exclusion_reason"].startswith("bot_username:")
    )
    ai_count = sum(
        1 for e in excluded if e["_exclusion_reason"].startswith("ai_generated:")
    )

    print(f"\nResults:")
    print(f"  Clean:                  {len(clean):,}")
    print(f"  Excluded (total):       {len(excluded):,}")
    print(f"    - Bot usernames:      {bot_count:,}")
    print(f"    - AI-generated leaks: {ai_count:,}")

    if excluded:
        print(f"\nExcluded entries:")
        for e in excluded:
            title = e.get("title", "?")[:80]
            line = f"  [{e['_exclusion_reason']}] {e.get('author', '?')} - {title}"
            print(line.encode("ascii", errors="replace").decode("ascii"))

    if dry_run:
        print("\n[DRY RUN] No files modified.")
        return {
            "total": len(entries),
            "clean": len(clean),
            "excluded": len(excluded),
            "bot_count": bot_count,
            "ai_count": ai_count,
        }

    # Backup original file (skip if backup already exists from a previous run)
    backup_path = HUMAN_PR_FILE.with_suffix(".jsonl.bak")
    if not backup_path.exists():
        shutil.copy2(HUMAN_PR_FILE, backup_path)
        print(f"\nBackup saved to {backup_path.name}")
    else:
        print(f"\nBackup already exists at {backup_path.name} (skipping)")

    # Write clean entries back to original file
    with open(HUMAN_PR_FILE, "w", encoding="utf-8") as f:
        for pr in clean:
            json.dump(pr, f)
            f.write("\n")
    print(f"Wrote {len(clean):,} clean PRs to {HUMAN_PR_FILE.name}")

    # Write excluded entries to quarantine
    QUARANTINE_DIR.mkdir(parents=True, exist_ok=True)
    mode = "a" if QUARANTINE_FILE.exists() else "w"
    with open(QUARANTINE_FILE, mode, encoding="utf-8") as f:
        for pr in excluded:
            json.dump(pr, f)
            f.write("\n")
    print(f"Wrote {len(excluded):,} excluded PRs to {QUARANTINE_FILE.name} (mode={mode})")

    # Verify
    with open(HUMAN_PR_FILE, "r", encoding="utf-8") as f:
        verify_count = sum(1 for line in f if line.strip())

    if verify_count == len(clean):
        print(f"\nVerification passed: {verify_count:,} lines")
    else:
        print(f"\nVerification FAILED: expected {len(clean):,}, got {verify_count:,}")

    return {
        "total": len(entries),
        "clean": len(clean),
        "excluded": len(excluded),
        "bot_count": bot_count,
        "ai_count": ai_count,
    }


# ============================================================================
# Main
# ============================================================================


def main():
    print("=" * 60)
    print("Human PR Cleaning Script")
    print("=" * 60)

    discover = "--discover" in sys.argv
    dry_run = "--dry-run" in sys.argv

    if discover:
        print("[DISCOVERY MODE]\n")
        entries = load_entries(HUMAN_PR_FILE)
        print(f"Loaded {len(entries):,} human PRs\n")
        discover_suspicious_authors(entries)
        print("\n" + "=" * 60)
        print("DISCOVERY COMPLETE")
        print("=" * 60)
        print("\nNext steps:")
        print("  1. Add any new bots to BOT_USERNAMES in this script")
        print("  2. python clean_human_prs.py --dry-run")
        print("  3. python clean_human_prs.py")
        return

    if dry_run:
        print("[DRY RUN MODE]\n")

    stats = clean_human_prs(dry_run=dry_run)

    print("\n" + "=" * 60)
    print("CLEANING COMPLETE" if not dry_run else "DRY RUN COMPLETE")
    print("=" * 60)

    if not dry_run:
        print(f"\nPipeline ready for classification:")
        print(f"  python scripts/classification/classify_prs.py")


if __name__ == "__main__":
    main()
